[package]
authors = ["Christian Visintin <christian.visintin1997@gmail.com>"]
categories = ["multimedia"]
description = "A telegram bot to be always up to date with the \"Papi\"'s news"
edition = "2021"
homepage = "https://github.com/veeso/big-luca-bot"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = ["bot", "telegram", "telegram-bot", "big-luca"]
license = "Unlicense"
name = "big-luca-bot"
readme = "README.md"
repository = "https://github.com/veeso/big-luca-bot"
version = "0.1.0"

[[bin]]
name = "big-luca-bot"
path = "src/main.rs"

[dependencies]
anyhow = "^1.0"
chrono = "^0.4"
feed-rs = "^1.1.0"
lazy-regex = "^2.3.0"
rand = "0.8.5"
reqwest = { version = "^0.11", features = [ "rustls-tls" ] }
teloxide = { version = "^0.10", features = ["macros", "auto-send", "rustls"] }
thiserror = "^1.0"
tokio = { version = "1.20.1", features = [ "full" ] }
tracing = "^0.1"
tracing-subscriber = "^0.2"

[dev-dependencies]
pretty_assertions = "^1.2.1"
