[package]
authors = ["Christian Visintin <christian.visintin1997@gmail.com>"]
categories = ["multimedia"]
description = "A telegram bot to be always up to date with the \"Papi\"'s news"
edition = "2021"
homepage = "https://github.com/veeso/big-luca-bot"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = ["bot", "telegram", "telegram-bot", "big-luca"]
license = "Unlicense"
name = "big-luca-bot"
readme = "README.md"
repository = "https://github.com/veeso/big-luca-bot"
version = "0.1.0"

[[bin]]
name = "big-luca-bot"
path = "src/main.rs"

[dependencies]

[dev-dependencies]
pretty_assertions = "^1.2.1"

